views/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

views/resume.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, abort, request, redirect, url_for, current_app
from model import ClientConnection
from utils import locate_ip
import datetime
import requests

blueprint = Blueprint('resume', __name__)


def register_ip(ip):
    if current_app.debug:
        ip = current_app.config.get('DEBUG_IP', '127.0.0.1')
    if ip == '127.0.0.1':
        return
    last_connection = ClientConnection.objects.filter(ip=ip).order_by('-date').first()
    now = datetime.datetime.now()
    if last_connection and now - last_connection.date < datetime.timedelta(hours=1):
        return
    v = locate_ip(ip)
    values = {'ip': ip}
    if v is not None:
        values.update(v)
    connection = ClientConnection(**values)
    connection.save()


@blueprint.route('/', methods=['POST', 'GET'])
def root():
    if request.method == 'GET':
        return redirect(url_for('root'))
    if request.form['g-recaptcha-response'] or current_app.debug:
        data = {
            'secret': current_app.config['RECAPTCHA_SECRET'],
            'response': request.form['g-recaptcha-response'],
            'remoteip': request.remote_addr
        }
        response = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
        no_robot = response.status_code == 200 and response.json().get('success', False)
        if no_robot or current_app.debug:
            register_ip(request.remote_addr)
            return render_template('resume.html')
    abort(404)


@blueprint.route('/printable/', methods=['GET'])
def printable_resume():
    import jsonpickle
    import calendar
    with open('static/content/resume.json') as json:
        data = jsonpickle.decode(json.read())
        extra = {
            'month_name': calendar.month_name[datetime.datetime.now().month],
            'year': str(datetime.datetime.now().year)
        }
        data.update(extra)
        return render_template('printable_resume.html', **data)

templates/printable_resume.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <style>
        body {
            font-family: sans-serif;
            line-height: 1.3;
            font-size: 1.1em;
        }

        h1 {
            font-size: 1.9em;
            font-family: "Trebuchet MS", sans-serif;
        }

        h2 {
            font-size: 1.6em;
            font-family: "Trebuchet MS", sans-serif;
        }

        h3 {
            font-size: 1.4em;
        }

        li {
            list-style-type: none;
            text-indent: -2em;
            padding-left: 2em;
        }

        li ul li {
            text-indent: -5em;
        }

        .content {
            padding-left: 3em;
            margin-top: 20px;
        }

        .content-title {
            font-size: 1.2em;
        }

        .skills {
            line-height: 1.5;
        }

        @media print {
        }

    </style>

    <title></title>
</head>
<body>

<div class="row column_wrapper">
  <div class="col-md-6 col-md-offset-3">
    <dif style="text-align: right;">
    <h1>{{ basics.name }}. Resume {{ year }}, {{ month_name }}</h1>
    <h2>{{ basics.label }}</h2>
    </dif>
    <hr>
    <h3>Basic information</h3>
    <ul>
        <li><strong>Email:</strong> {{ basics.email }}</li>
        <li><strong>Phone number:</strong> {{ basics.phone }}</li>
        <li><strong>Website:</strong> {{ basics.website }}</li>
        <li><strong>City:</strong> {{ basics.location.city }}</li>
        <li>
            <strong>Languages</strong>
            <ul>
                {% for language in languages %}
                    <li>{{ language.language }}. {{ language.fluency }}</li>
                {% endfor %}
            </ul>
        </li>
    </ul>

    <h3>Skills</h3>

    <ul>
      {% for skill in skills %}
          <li class="skills">{{ skill.name }} {% if skill.keywords  %}({% for kword in skill.keywords %}{{ kword }}{% if not loop.last %}, {% endif %}{% endfor %}){% endif %}</li>
      {% endfor %}
    </ul>

    <h3>Works</h3>

      {% for w in work %}
        <p class="content">
            <strong><span class="content-title">{%  if w.position %}{{ w.position }} in {% endif %}{{ w.company }}</span><br>
            {% if w.website %}{{ w.website }}, {% else %} {% endif %}{{ w.startDate }} - {% if w.endDate %}{{ w.endDate }}{% else %}Nowadays{% endif %}</strong><br>
            {{ w.summary }}
        </p>
      {% endfor %}

    <h3>Education</h3>

        {% for ed in education %}
        <p class="content">
            <strong><span class="content-title">{{ ed.studyType }}, {{ ed.area }}</span></strong><br>
            {{ ed.institution }}, {{ ed.startDate }} - {% if ed.endDate %}{{ ed.endDate }}{% else %}Nowadays{% endif %}
        </p>
        {% endfor %}

    <h3>Projects</h3>

        {% for proj in projects %}
        <p class="content">
            <strong><span class="content-title">{{ proj.name }}</span></strong><br>
            {% if proj.website %}{{ proj.website }}, {% endif %}{% if proj.startDate %}{{ proj.startDate }} - {% if proj.endDate %}{{ proj.endDate }}{% else %}Nowadays{% endif %}{% endif %}{% if proj.website or proj.startDate %}<br>{% endif %}
            {{ proj.summary }}
        </p>
        {% endfor %}

    <h3>Volunteer</h3>
        {% for vol in volunteer %}
        <p class="content">
            <strong><span class="content-title">{{ vol.position }} in {{ vol.organization }}</span></strong><br>
            {% if vol.website %}{{ vol.website }}, {% endif %}{{ vol.startDate }} - {% if vol.endDate %}{{ vol.endDate }}{% else %}Nowadays{% endif %}<br>
            {{ vol.summary }}
        </p>
        {% endfor %}

    <h3>Interests</h3>
        <p class="content">
          {% for interest in interests %}{{ interest.name }}{% if not loop.last %}, {% endif %}{% endfor %}.
        </p>
  </div>
</div>

</body>
</html>

templates/resume.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<!--[if lte IE 8]>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
<!--<![endif]-->
<!--[if lte IE 8]>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/layouts/blog-old-ie.css') }}">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/layouts/blog.css') }}">
<!--<![endif]-->

    <script>
        var resume_url = "{{ url_for('static', filename='content/resume.json') }}";
    </script>
    
    <script src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/handlebars.runtime-v3.0.3.js') }}"></script>
    <script src="{{ url_for('static', filename='js/templates.js') }}"></script>
    <script src="{{ url_for('static', filename='js/2html.js') }}"></script>

    <title>Resume</title>    
</head>
<body>

<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header" id="mainsection"></div>
        <div class="submenu">
            <p>
                <!-- resume/printable/ -->
                <a href="{{ url_for('resume.printable_resume') }}">Printable version</a> - <a href="../static/content/resume.json">JSON Resume</a>
            </p>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div class="posts">
            <section class="post" id="summary"></section>
            <section class="post" id="skills"></section>
            <section class="post" id="works"></section>
            <section class="post" id="education"></section>
            <section class="post" id="projects"></section>
            <section class="post" id="volunteer"></section>
            <section class="post" id="basic-information"></section>
            <section class="post" id="interests"></section>
        </div>
    </div>
</div>    
</body>
</html>

templates/watch.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

    <link rel="stylesheet" href="{{ url_for('static', filename='styles/global.css') }}">
    <script>
        function submit_the_form() {
            if (document.getElementById("g-recaptcha-response").value !== "") {
                document.getElementById("aaccess").style.visibility='hidden';
                document.forms['the_form'].submit();
            } else document.getElementsByClassName('advice')[0].style.visibility='visible';
        }
    </script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
<div class="absolute-center">
    <form action="./resume/" method="POST" name="the_form">
        <p>
            Next page contains personal information and I have to assure myself that you are not a robot. Please, if
                you are a human being, still having some doubts about it, check the next box:
        </p>
        <img src="{{ url_for('static', filename='img/hand.gif') }}" class="advice" width="170px">
        <div class="g-recaptcha right-align" data-sitekey="6Le3AAsTAAAAAP8pMgC1k8ddzBrn-YlPMaRGE65S"></div>
        <div class="bottom-align" align="right">
            <a id="aaccess" href="#" onclick="submit_the_form();">Access to my resume</a>
        </div>
    </form>
</div>
</body>
</html>